#pragma once

#define OTOMARKET_LICENSE_SDK_VERSION_MAJOR 1
#define OTOMARKET_LICENSE_SDK_VERSION_MINOR 1
#define OTOMARKET_LICENSE_SDK_VERSION_PATCH 0
#define OTOMARKET_LICENSE_SDK_VERSION_STRING "1.1.0"
